#!/bin/bash
###############################################################################
#
# Bash Remediation Script for No profile (default benchmark)
#
# Profile Description:
# Not available
#
# Profile ID:  (null)
# Benchmark ID:  RHEL-6
# Benchmark Version:  0.1.49
# XCCDF Version:  1.1
#
# This file was generated by OpenSCAP 1.3.2 using:
# $ oscap xccdf generate fix --profile (null) --fix-type bash xccdf-file.xml
#
# This Bash Remediation Script is generated from an OpenSCAP profile without preliminary evaluation.
# It attempts to fix every selected rule, even if the system is already compliant.
#
# How to apply this Bash Remediation Script:
# $ sudo ./remediation-script.sh
#
###############################################################################

